---
title: "Homework 3 work"
author: "Arantza Lira"
format: html
editor: visual
---
link to Github: https://github.com/arara4191/ENVS-193DS_homework-03.git 

```{r-loading packages}
#loading in necessary packages

library("tidyverse")
library("here")
library("janitor")
library("gt")

```

```{r reading in data}
#read in my biking speed data
#use here package to ensure reproducibility of the code

bike_data <- read_csv(here("data", "Biking_Speed_Data.csv"))


```

#Problem 1. Personal Data
##a. 

I can group my biking trips into trips where I listened to fast or slow music and find the average biking speed (mph) of each group. Since fast music usually gives me more energy, I think this might translate to biking faster when the music is faster.

##b. 

```{r}
#cleaning bike data column names
bike_data_clean <- clean_names(bike_data)

#creating a separate data frame to store data exploration info
bike_data_mean_exp <- bike_data_clean %>%
  group_by(music) %>% #creating groups based on slow/fast music
  summarize(mean_mph = mean(average_biking_speed_mph)) #summarizing mean speed of each group


#creating boxplot to visualize average biking speed based on music
ggplot(data = bike_data_clean,#creating base plot with cleaned data    
       aes(x = music,             
           y = average_biking_speed_mph,            
           fill = music)) +          
  geom_boxplot() +  #creates a box plot
  geom_jitter(height = 0,#prevents jitter from moving points along vertically
              width = 0.2) + #narrows spread of jitter along x-axis
  labs( x = "Music",
        y = "Average Biking Speed (mph)",
        title = "Relationship between Music and Biking Speed(mph)") +
  geom_point() +
  scale_fill_manual(values = c("fast" = "red", 
                                "slow" = "pink"))+ # manually changing colors
  theme(legend.position = "none") # removes legend



```





